---
title: "FATE-HD tutorial - Installation"
# author: "LECA Grenoble"
# date: "10/05/2016"
output:
  html_document:
    theme: lumen
    highlight: zenburn
    number_sections: no
    toc: yes
    toc_float:
      collapsed: false
      smooth_scroll: false
---

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

<br/> <br/>

"*The recurring suggestions are that models should explicitly (i) include spatiotemporal dynamics; (ii) consider
multiple species in interactions and (iii) account for the processes shaping biodiversity distribution.*"

`FATE-HD` is a "*a biodiversity model that meets this challenge at regional scale by combining phenomenological and process-based approaches and using well-defined plant functional group*". ([Boulangeat, 2014](http://www.will.chez-alice.fr/pdf/BoulangeatGCB2014.pdf "Boulangeat, I., Georges, D., Thuiller, W., FATE-HD: A spatially and temporally explicit integrated model for predicting vegetation structure and diversity at regional scale. Global Change Biology, 20, 2368–2378."))

<br/> <br/>

# <i class="fa fa-exclamation-circle"></i> Before starting
This tutorial has been designed for a `UNIX` based platform. It should fit with all `linux` distributions and with slight modifications with `mac` OS. Some files and links are given to install the program on `Windows` but some adaptations might be needed.

<br/>

- As `FATE-HD` depends on
    - [openMP](http://www.openmp.org/) and [boost](https://www.boost.org/) libraries,
    - [GDAL](http://www.gdal.org/, "Geospatial Data Abstraction Library")
    - XCode [Command Line Tools](https://developer.apple.com/xcode/) (for `mac` OS),
    - and needs a compiler (either [gcc](https://gcc.gnu.org/) preferentially or [clang](http://clang.llvm.org/)),
- and due to the difficulty to provide a valid installation procedure *for each `mac` version*,

we decided to

- try to **provide directly the binary files for UNIX and mac OS**
- provide with the sources the supplementary files for [openMP](http://www.openmp.org/), [boost](https://www.boost.org/) and [GDAL](http://www.gdal.org/, "Geospatial Data Abstraction Library") libraries :  
in that way, only a compiler should be installed (and [GTK-3.0](http://www.gtk.org/) for the graphical interface) to recompile the program if needed.

<br/>

We detail below 3 cases

1. the **easy way** : retrieve directly the binary files
2. the **harder-but-not-so-much way** : get a compiler to recompile from sources
3. the **extrem way** with indications to install all needed libraries depending on the OS 


Please keep in mind that in any case, **sources are completely available on the [project source forge page](https://sourceforge.net/projects/biomove/)**.

<br/> <br/>

# <i class="fas fa-people-carry"></i> Install - Easy way : Get binaries

<br/>

Files can be obtained from the [project source forge page](https://sourceforge.net/projects/biomove/), by using the [svn](https://subversion.apache.org/) solution.

Open a terminal and create a working directory :

```R
mkdir fatehd_tutorial
cd fatehd_tutorial
```

Then type :
```Shell
svn checkout svn://svn.code.sf.net/p/biomove/code/FATEHDD_STABLE/BINARIES/ ./FATE_BinaryFiles/
```

You should now have all the last stable `FATE-HD` binary files. Use the one corresponding to your OS.

<br/> <br/>

# <i class="fa fa-parachute-box"></i> Install - Harder-but-not-so-much way : Compile sources

<br/>

###  Get package source code

Open a terminal and create a working directory :

```Shell
mkdir fatehd_tutorial
cd fatehd_tutorial
```

Then type :
```Shell
svn checkout svn://svn.code.sf.net/p/biomove/code/FATEHDD_STABLE/ ./fateHD_source/
```
**NOTE :** This tutorial is based on the latest stable version of the software available at the moment of writing. All following explanations will be based on this release.  
If you wish to download any specific version, you can run the following line of code (outcommented with ##) and specifying the version number (here, you want the 138th revision) :
```Shell
## svn checkout -r 138 svn://svn.code.sf.net/p/biomove/code/STABLE/ fateHD_source
```

You should have a directory called *fateHD_source* :
```Shell
ls
```

<br/> <br/>

###  Check for c++ compiler

`FATE-HD` is written in `c++` so we need an adapted compiler to be able to produce binaries. Here we choose to work with [gcc / g++](https://gcc.gnu.org/).

**On linux OS**, it should be available by default but you can check by typing :
```Shell
g++ -v
```
It should print you some details on which version of `gcc/g++` is installed.

If you get ``g++: unknown commande`` message, type the following commands to install `gcc/g++` version 4.8 :
```Shell
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-4.8 g++-4.8
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
```

**On mac OS**, `g++` is generally available through [Macports](https://www.macports.org/) and `xcode Command Line Tools` :

- `MacPorts` can be downloaded from [this webpage](https://www.macports.org/install.php) by selecting your version of OS X  
(*this installation can take a long time*).
- `xcode Command Line Tools` can be install by typing :
```Shell
xcode-select --install
```
You can choose to install only the `Command Line Tools` (and not complete [xcode](https://developer.apple.com/xcode/)).

Then check installation of `g++` typing ``g++ -v`` (see above). If you don't :
```Shell
sudo port install gcc48
```

**NOTE :** **The gcc version depends on your mac version!**  
Here, as an example, `gcc 4.8` works for `mac Mavericks (10.9)`.

Even after having installed `gcc`, it might not be the default compiler defined on your computer. Typing ``g++ -v`` might still indicate you `clang` as default. The following command should indicate you which versions of `gcc` are available on your computer and which one is active (if `clang` is the default compiler, it should be *none* selected) :
```Shell
port select --list gcc
```

To select `gcc 4.8`, run the command:
```Shell
sudo port select --set gcc mp-gcc48
```

Now typing ``g++ -v`` should give you the right answer (at least the one we want!).


**On windows OS**, you can install it from directory *fateHD_source/SUPP_MAT/INSTALL_SOFT/GCC/* with the file `tdm64-gcc-5.1.0-2.exe`.



**NOTE :** The `C++` code depends on a version which works only with `gcc` version >= `4.7`. If you install a version anterior to this one (but we strongly advise you not to), you will just need to make a slight adjustement into the compilation file.

```Shell
cd fateHD_source/MAKEFILES/
```

Open the files corresponding to your OS, search for the element : **`-std=c++11`** and replace it with **`-std=c++0x`**. That's it.

<br/> <br/>

###  Check for GTK+-3.0

<br/>

**This is needed onl if you want to compile and use the graphical interface.**

**On linux OS**, you can install it by typing :
```Shell
sudo apt-get install libgtk-3-dev
```

**On mac OS**, you can install it from directory *fateHD_source/SUPP_MAT/INSTALL_SOFT/GTK/* :

- extract `gtk+-bundle_3.6.4_20130630_macosx.tar.bz2`
- create a folder named *gtk3* at the root
- copy all the files within this directory

**On windows OS**, you can install it from directory *fateHD_source/SUPP_MAT/INSTALL_SOFT/GTK/* :

- extract `gtk+-bundle_3.6.4-20130513_win64.zip`
- create a folder named *gtk3* at the root
- copy all the files within this directory

<br/> <br/>

###  Compile sources

<br/>

Once you have successfully installed your c++ compiler, you should be able to create `FATE-HD` binaries.

**On linux or mac OS**,

```Shell
cd fateHD_source/
chmod +x FateHD_compilation.sh
./FateHD_compilation.sh
```

**On windows OS**, open a MinGW command prompt and type :
```Shell
cd fateHD_source/
mingw32-gcc -f MAKEFILES/MakefileWindows
mingw32-gcc -f MAKEFILES/MakefileWindows_GTK
```

*------------------------------------------*

If it succeeds, you should have a new binary file in the *fateHD_source/BINARIES/* directory. The file name takes into account the OS system, and the `FATE-HD` version (for example : *FATEHDD_6.0-0_UNIX*).
```Shell
ls ./BINARIES/
```
Let's copy this file in our working directory (but note that you will always need to copy this file in your working directories, e.g. in the following tutorial exercises) :

```Shell
cd ..
cp fateHD_source/BINARIES/FATEHDD_6.0-0_UNIX ./
```

At this step you have a functional version of the latest stable version of `FATE-HD`.

<br/> <br/>

# <i class="fas fa-boxes"></i>  Install - Extrem way : Install all libraries

<br/>

###  Check for Boost library

<br/>

`FATE-HD` needs the [boost library](https://www.boost.org/), which is a series of C++ source libraries, to be compiled and run. 

**On linux** you should be able to install this library from official depot :
```Shell
sudo apt-get install libboost-all-dev
```
**On mac** the installation if a little bit longer, because you have to build `boost` from files. (`Macports` provides an installation for `boost` but which is not complete, at least for what we need in our case...).

From the [boost GIT repository](http://sourceforge.net/projects/boost/files/boost/) :

1. select the `boost` version you want, and then download the *tar.gz* corresponding file ;
2. unpack and go into the directory :
```Shell
tar -xzf boost_1_59_0.tar.gz
cd boost_1_59_0
```
3. configure and build *bjam* :
```Shell
./bootstrap.sh --prefix=/opt/local/
```
4. build :
```Shell
./b2
```
5. install :
```Shell
./b2 install
```

**NOTE :**

- you then need to tell your *Makefile* where it can find the `boost` libraries and files :
- before running `FATE-HD`, you also need to remind your computer where are the `boost` libraries and files so the compiled software can also find them :
```Shell
export DYLD_LIBRARY_PATH=~/where/is/boost_1_59_0/lib/:$DYLD_LIBRARY_PATH
```

[//]: # (**NOTE :**)

[//]: # ( - especially for `mac`, depending on which installation tool has been used (`MacPorts`, or `Homebrew`, or `Fink`), paths in the **Makefile** might need to be adapted, because those tools do not install modules at the same place. For example :)
 
[//]: # (    - in */opt/local/* for `MacPorts`
    - in */usr/* for `Homebrew`
    - in */sw/* for `Fink`...)


[//]: # (the following command should install the [boost library](https://www.boost.org/), provided you have `MacPorts` installed on your mac :
```Shell
sudo port install boost 
```)

<br/> <br/>

###  Check for GDAL library

<br/> 

**On linux** you should be able to install this library from official depot :
```Shell
sudo apt-get install build-essential libgdal-dev
```
**On mac** the installation if a little bit longer, because you have to install several modules. Successive steps are detailed below and can also be found [HERE](https://sites.google.com/site/eospansite/installinggdalonmacosx). The idea is to install the [Unix Compatibility Frameworks](http://www.kyngchaos.com/software/frameworks) which includes various Unix image format and GIS libraries for `mac` OS.

1. Download [HERE](https://sites.google.com/site/eospansite/installinggdalonmacosx) the **GDAL complete** framework.
2. Open the *.dmg* file and install both *gdal.pkg* and *numpy.pkg* files.
3. Open a terminal, write the command below and hit *Return* :
```Shell
export PATH=/Library/Frameworks/GDAL.framework/Programs:$PATH
```
4. To check for complete installation, type in the console :
```Shell
gdalinfo --version
```

**NOTE :** you may have an error message if your `mac` version is prior to 10.8... No worries ! In that case, please follow the steps below :

1. You can find [HERE](http://www.kyngchaos.com/software/archive) previous versions for the different modules that have to be installed, with indications about compatibilities with `mac` OS version. You need to download and install the following packages in the right order :
      - PROJ framework
      - GEOS framework
      - UnixImageIO framework
      - SQLite3 framework
      - GDAL framework
2. For each, open the *.dmg* file and install the *.pkg* file.
3. Open a terminal, write the command below and hit *Return* :
```Shell
export PATH=/Library/Frameworks/GDAL.framework/Programs:$PATH
```
4. To check for complete installation, type in the console :
```Shell
gdalinfo --version
```

<br/> <br/>

# Conclusion

This document is just meant to present the installation of `FATE-HD`. Other documents will present and detail examples of `FATE-HD` simulations and utilization.

This document is in the alpha version so any comment is more than welcome. If you have any question relative to `FATE-HD` or if you encounter some issue to run your simulation you should send a mail to `FATE-HD` help mailing list at [fate-hd@googlegroups.com]().
 


